spring.application.name=SistemaCompras
spring.datasource.url= ${DATABASE_URL}
spring.datasource.username= ${DATABASE_USER}
spring.datasource.password= ${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host = ${REDIS_HOST}
spring.redis.port = ${REDIS_PORT}
api.security.token.secret=${TOKEN_PASSWORD}

api.origin.url =${ORIGIN_URL}